# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

trigger:
- main
 
pool:
  vmImage: ubuntu-latest
 
strategy:
  matrix:
    Python310:
      python.version: '3.10'
    Python311:
      python.version: '3.11'
    Python312:
      python.version: '3.12'
 
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
 
  - script: |
    python -m pip install --upgrade pip 

    pip install -r requirements.txt 

    displayName: 'Install dependencies'  

 
 - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-$(python.version).zip 
      replaceExistingArchive: true 

 

  - task: PublishBuildArtifacts@1 

    inputs: 

      PathtoPublish: '$(Build.ArtifactStagingDirectory)' 

      ArtifactName: 'drop' 

      publishLocation: 'Container' 

 

  - script: | 

      pip install pytest pytest-azurepipelines 

      pytest 

      displayName: 'pytest'
